rood: "(255, 0, 0, 255)"
blauw: "(0, 0, 255, 255)"
groen: "(0, 255, 0, 255)"
geel: "(255, 255, 0, 255)"

msgs:
  mean_reaction_time: "Je gemiddelde reactietijd is:"
  instruction: |
    "Bedankt voor uw deelname aan deze taak. Kijk naar de gekleurde woorden.\n"
    "Als woordbetekenis en kleur NIET overeenkomen druk dan op `<`.\n"
    "Als woordbetekenis en kleur overeenkomen druk dan op `>`.\n" 
    "Druk op spatie om te starten",
