# main stroop words
words:
  red: "(255, 0, 0, 255)"
  blue: "(0, 0, 255, 255)"
  green: "(0, 255, 0, 255)"
  yellow: "(255, 255, 0, 255)"

# messages
msgs:
  mean_reaction_time: "Your average reaction time is:"
  instruction_headline: |
    Thank you for participating in this task.

  press_down_instruction: |
    Press the arrow down key
    and hold it to start
    once the cross appears.

  congruent_reaction_color_focus: |
    Press the arrow right
    key if the color of top word matches
    the text below.

  incongruent_reaction_color_focus: |
    Press the arrow left
    key if the color of top word does NOT match
    the text below.

  instruction_footer: |
    Press the space key to start.

  instruction_headline_classical: |
    Thank you for participating in this task. We ask you now to please read 
    color words from a list and speak out loud the color the word is printed
    in and NOT the word itself. For example, if you see the word "red" printed
    in blue, you should say "blue".
