# main stroop words
red: "(255, 0, 0, 255)"
blue: "(0, 0, 255, 255)"
green: "(0, 255, 0, 255)"
yellow: "(255, 255, 0, 255)"

# messages
msgs:
  mean_reaction_time: "Your average reaction time is:"
  instruction: |
    "Thank you for participating in this task. Please look at the coloured words."
    "If word meaning and colour do NOT match then press `<`.\n"
    "If word meaning and colour match please press `>`.\n" 
    "Press space to start"
